# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Advance Upstream Forks

on:
  schedule:
    # Every hour
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  advance_iree-llvm-fork:
    # Don't run this in everyone's forks.
    if: github.repository == 'iree-org/iree'
    name: "Advance iree-llvm-fork"
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          repository: iree-org/iree-llvm-fork
          ref: main

      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/llvm/llvm-project.git
          git pull --ff-only upstream main
      - name: Pushing changes
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: main
          repository: iree-org/iree-llvm-fork

  advance_iree-mhlo-fork:
    # Don't run this in everyone's forks.
    if: github.repository == 'iree-org/iree'
    name: "Advance iree-mhlo-fork"
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          repository: iree-org/iree-mhlo-fork
          ref: master

      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/tensorflow/mlir-hlo.git
          git pull --ff-only upstream master
      - name: Pushing changes
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: master
          repository: iree-org/iree-mhlo-fork

  advance_iree-tf-fork:
    # Don't run this in everyone's forks.
    if: github.repository == 'iree-org/iree'
    name: "Advance iree-tf-fork"
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repository
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          repository: iree-org/iree-tf-fork
          ref: master

      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/tensorflow/tensorflow.git
          git pull --ff-only upstream master
      - name: Pushing changes
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: master
          repository: iree-org/iree-tf-fork
