# Builds the TFLite Java Bindings Android Library using the gradle-android
# Docker image.
name: Build TFLite Android Library

on:
  workflow_dispatch:

jobs:
  build_android_with_docker:
    runs-on: ubuntu-20.04
    env:
      ANDROID_CONTAINER: "gcr.io/iree-oss/gradle-android@sha256:c4c3450ee634a3fc6b75fa73b24f0d97d8b295e0cf599aab63dd5f12a8746333"
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
        with:
          submodules: true
      - name: Execute Android Build
        run: |
          docker run --rm \
          -w=/work \
          -v $PWD:/work \
          "${ANDROID_CONTAINER}" \
          bash -c build_tools/gradle/build_tflite_android_library.sh
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          path: ./runtime/bindings/tflite/java/build/outputs/aar/*.aar
          retention-days: 1
