# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - Linux x64 gcc

on:
  pull_request:
    paths:
      - ".github/workflows/ci_linux_x64_gcc.yml"
  schedule:
    # Weekday mornings at 09:15 UTC = 01:15 PST (UTC - 8).
    - cron: "15 9 * * 1-5"
  workflow_dispatch:
  workflow_call:

jobs:
  linux_x64_gcc:
    if: ${{ github.repository_owner == 'iree-org' || github.event_name != 'schedule' }}
    runs-on: ubuntu-24.04
    container: ghcr.io/iree-org/cpubuilder_ubuntu_jammy@sha256:dfaf99be6f3adf3d7e404ca8e41e545f5353ab694037f627d2170f49f688504f
    defaults:
      run:
        shell: bash
    env:
      BUILD_DIR: build-gcc
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true
      - name: "Building IREE with gcc"
        env:
          CC: gcc-11
          CXX: g++-11
          CMAKE_BUILD_TYPE: Release
          IREE_TARGET_BACKEND_WEBGPU_SPIRV: OFF
          IREE_BUILD_SETUP_PYTHON_VENV: ${{ env.BUILD_DIR }}/.venv
        run: ./build_tools/cmake/build_all.sh "${BUILD_DIR}"

      - name: Post to Discord on Failure
        uses: sarisia/actions-status-discord@b8381b25576cb341b2af39926ab42c5056cc44ed # v1.15.5
        if: failure() && github.ref_name == 'main' && github.repository_owner == 'iree-org'
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "The ${{ github.workflow }} workflow failed"
          url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}"
