# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: PkgCI Test AMD MI300
on:
  workflow_call:
    inputs:
      artifact_run_id:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""

jobs:
  test_mi300:
    runs-on: linux-mi300-gpu-1
    container:
      image: rocm/dev-ubuntu-22.04:6.3
      options: --user root --device=/dev/kfd --device=/dev/dri --ipc=host --group-add video --group-add $render_gid --cap-add=SYS_PTRACE --security-opt seccomp=unconfined
    env:
      PACKAGE_DOWNLOAD_DIR: ${{ github.workspace }}/.packages
      BUILD_DIR: build-tests
      VENV_DIR: ${{ github.workspace }}/.venv
      CC: clang
      CXX: clang++
      IREE_CPU_DISABLE: 1
      IREE_VULKAN_DISABLE: 1
      IREE_CUDA_ENABLE: 0
      IREE_HIP_ENABLE: 1
      IREE_HIP_TEST_TARGET_CHIP: "gfx942"
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang lld git
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: false
      - name: Check out runtime submodules
        run: |
          git config --global --add safe.directory /__w/iree/iree
          ./build_tools/scripts/git/update_runtime_submodules.sh
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          # Must match the subset of versions built in pkgci_build_packages.
          python-version: "3.11"
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: linux_x86_64_release_packages
          path: ${{ env.PACKAGE_DOWNLOAD_DIR }}
      - name: Setup base venv
        run: |
          ./build_tools/pkgci/setup_venv.py ${VENV_DIR} \
            --artifact-path=${PACKAGE_DOWNLOAD_DIR} \
            --fetch-gh-workflow=${{ inputs.artifact_run_id }}

      - name: Build tests
        run: ./build_tools/pkgci/build_tests_using_package.sh ${VENV_DIR}/bin
      - name: Run GPU tests
        env:
          CTEST_PARALLEL_LEVEL: 2
          IREE_CTEST_LABEL_REGEX: ^requires-gpu|^driver=hip$
          IREE_AMD_RDNA3_TESTS_DISABLE: 1
          IREE_NVIDIA_GPU_TESTS_DISABLE: 0
          IREE_NVIDIA_SM80_TESTS_DISABLE: 1
          IREE_MULTI_DEVICE_TESTS_DISABLE: 0
        run: ./build_tools/cmake/ctest_all.sh ${BUILD_DIR}
