# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: PkgCI Test TensorFlow (GPU)
on:
  workflow_call:
    inputs:
      artifact_run_id:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""

jobs:
  linux_x86_64:
    name: Linux (x86_64)
    runs-on:
      - self-hosted # must come first
      - runner-group=${{ github.event_name == 'pull_request' && 'presubmit' || 'postsubmit' }}
      - environment=prod
      - gpu
      - os-family=Linux
    container:
      image: docker://gcr.io/iree-oss/nvidia@sha256:892fefbdf90c93b407303adadfa87f22c0f1e84b7e819e69643c78fc5927c2ba
      options: --gpus all
      env:
        NVIDIA_DRIVER_CAPABILITIES: all
        PACKAGE_DOWNLOAD_DIR: ${{ github.workspace }}/.packages
        IREERS_ARTIFACT_DIR: ${{ github.workspace }}/artifacts
        VENV_DIR: ${{ github.workspace }}/.venv
        IREE_VULKAN_DISABLE: 0
        IREE_LLVM_CPU_DISABLE: 1
        IREE_NVIDIA_GPU_TESTS_DISABLE: 0
    steps:
      - name: Checking out repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          submodules: false
      - name: "Marking git safe.directory"
        run: git config --global --add safe.directory '*'
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4.7.0
        with:
          # Must match the subset of versions built in pkgci_build_packages.
          python-version: '3.11'
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a  # v3.0.2
        with:
          name: linux_x86_64_release_packages
          path: ${{ env.PACKAGE_DOWNLOAD_DIR }}
      - name: Setup base venv
        run: |
          ./build_tools/pkgci/setup_venv.py ${VENV_DIR} \
            --artifact-path=${PACKAGE_DOWNLOAD_DIR} \
            --fetch-gh-workflow=${{ inputs.artifact_run_id }}
      - name: Run tests
        run: |
          source ${VENV_DIR}/bin/activate
          build_tools/scripts/check_cuda.sh
          build_tools/scripts/check_vulkan.sh
          build_tools/cmake/run_tf_tests.sh
