# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Postsubmit

on:
  push:
    branches:
     - main
  workflow_dispatch:
  pull_request: # TODO: remove this

jobs:
  build_runtime:
    uses: ./.github/workflows/build_runtime_cmake.yml
    with:
      build-dir: build-runtime

  test_runtime:
    uses:  ./.github/workflows/test_runtime.yml
    with:
      build-dir: build-runtime
