# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Presubmit

on:
  workflow_dispatch:
  # pull_request_target:
  # TODO: remove this
  pull_request:

jobs:
  dispatch:
    runs-on: ubuntu-20.04
    steps:
    - name: "Invoke workflow :: all the builds"
      uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7  # v1
      with:
        # Hack attack. This has to be a workflow that *already* exists in the
        # repository. I miss buildkite's "pipeline upload" :'-(
        workflow: Buildifier
        token: ${{ secrets.WRITE_ACCESS_TOKEN }}
        # Note that we're using the workflow file from the base branch (e.g.
        # 'main'), but telling the workflow to checkout code from the PR itself.
        # TODO: actually do this
        ref: "${{ github.ref }}"
        inputs: '{"runner-group": "presubmit", "ref": "${{ github.head_ref }}" }'
