# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

on:
  workflow_call:
    inputs:
      build-dir:
        required: true
        type: string


env:
  IREE_DOCKER_WORKDIR: "/usr/src/github/iree"

jobs:
  build_runtime:
    name: "Test runtime"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e  # v2
        with:
          submodules: true
      - name: "Downloading runtime build directory"
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741  # v3.0.0
        with:
          name: "${{ inputs.build-dir }}.tar"
          path: "${{ inputs.build-dir }}.tar"
      - name: "Extract archive"
        run: tar -xf ${{ inputs.build-dir }}.tar ${{ inputs.build-dir }}
      - name: "Testing runtime"
        run: |
          docker run --user="$(id -u):$(id -g)" \
            --volume="$PWD:$IREE_DOCKER_WORKDIR" \
            --workdir="$IREE_DOCKER_WORKDIR" \
            --env IREE_VULKAN_DISABLE=1 \
            --rm \
            gcr.io/iree-oss/base@sha256:9d742e01507c292def852cbfebfae71412cff94df0ab2619f61f9a5a2a98f651 \
            ./build_tools/cmake/ctest_all.sh \
            "${{ inputs.build-dir }}"
