# Publishes a draft snapshot, after performing validation to make sure all linux
# packages are stable.
name: Validate and Publish Release

on:
  workflow_dispatch:
    inputs:
      release_id:
        description: 'Release id to publish'
        required: true
      package_version:
        description: 'Version of the package'
        required: true
      build_run_id:
        description: 'Run ID for the build_package.yml workflow that triggered this workflow'
        required: true

jobs:
  validate_packages:
    name: "Validate packages"
    # TODO(jennik): Look into testing windows and macos builds.
    runs-on: ubuntu-18.04
    steps:
      - name: Download packages
        id: download_packages
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.WRITE_ACCESS_TOKEN}}
          workflow: build_package.yml
          run_id: ${{ github.event.inputs.build_run_id }}
      - name: Display downloaded files
        run: |
          pwd
          ls -R
      - name: Set up python
        id: set_up_python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python packages
        id: install_python_packages
        run: |
          python -m pip install -f file://$PWD/artifact/ iree-compiler-snapshot iree-jax-snapshot iree-runtime-snapshot iree-tools-tflite-snapshot iree-tools-tf-snapshot iree-tools-xla-snapshot
      - name: Run tools with basic commands
        id: run_tools_with_basic_commands
        run: |
          tar -xf artifact/iree-dist-snapshot-${{ github.event.inputs.package_version }}-linux-x86_64.tar.xz
          cd bin
          ./iree-benchmark-module --help
          ./iree-benchmark-trace --help
          ./iree-flatcc-cli --help
          ./iree-opt --help
          ./iree-run-mlir --help
          ./iree-run-module --help
          ./iree-run-trace --help
          ./iree-tblgen --help
          ./iree-translate --help

  publish_release:
    name: "Publish release"
    needs: validate_packages
    runs-on: ubuntu-18.04
    steps:
      - name: Publish Release
        id: publish_release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_TOKEN }}
        with:
          release_id: ${{ github.event.inputs.release_id }}

      - name: Checking out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          # Get all history. Otherwise the latest-snapshot branch can't be
          # fast-forwarded.
          fetch-depth: 0

      - name: Updating latest-snapshot branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.WRITE_ACCESS_TOKEN }}
          branch: latest-snapshot
