site_name: IREE
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/ghost
  favicon: assets/images/favicon.png
  logo: assets/images/favicon.png
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.tracking  # TODO(scotttodd): join mkdocs-material insiders for this

    # TODO(scotttodd): decide if we want this
    # - navigation.tabs
    # - navigation.tabs.sticky  # insiders only

    - navigation.sections
    - navigation.top

    # Insiders only: navigation indices
    #     supply index.md page under each section
    #     list each index.md page in the `nav:` section below
    # - navigation.indexes

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_url: https://github.com/google/iree
repo_name: google/iree
edit_uri: ""  # Omit edit button (linking to GitHub) from each document

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/google/iree
      name: IREE on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/26P4xW4
      name: IREE Discord Server
  generator: false  # TODO(scotttodd): join mkdocs-material insiders for this

extra_css:
  - assets/stylesheets/extra.css

copyright: Copyright &copy; 2021 Google LLC

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true  # TODO(scotttodd): icon: https://fonts.google.com/icons?selected=Material+Icons+Outlined:link

# Navigation with explicit ordering and nesting.
# https://www.mkdocs.org/user-guide/configuration/#nav
nav:
  - Home: 'index.md'
  - 'Frontends':
      - TensorFlow: 'frontends/tensorflow.md'
      - TensorFlow Lite: 'frontends/tensorflow-lite.md'
      - JAX: 'frontends/jax.md'
  - 'Backends':
      - CPU - LLVM: 'backends/cpu-llvm.md'
      - GPU - Vulkan: 'backends/gpu-vulkan.md'
  - 'Building from source':
      # - 'building-from-source/index.md'  # TODO(scotttodd): insiders + navigation.indexes
      - 'building-from-source/getting-started.md'
      - Python bindings: 'building-from-source/python.md'
      - Android cross-compilation: 'building-from-source/android.md'
  - 'Bindings':
      - Python: 'bindings/python.md'
      - C API: 'bindings/c-api.md'
      - TensorFlow Lite: 'bindings/tensorflow-lite.md'
  - 'Community':
      - Projects: 'community/projects.md'
